apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: two-tcp
  namespace: default
  annotations:
    ingress.appscode.com/type: HostPort
    ingress.appscode.com/node-selector: '{ "kubernetes.io/hostname": "minikube" }'
spec:
  rules:
  - tcp:
      port: 80
      noTLS: true
      backend:
        serviceName: nginx
        servicePort: 80
  - tcp:
      port: 443
      noTLS: true
      backend:
        serviceName: nginx
        servicePort: 443
